### ISSUE TITLE
occur error when i run your wine-docker

### ISSUE THREAD

**Issue by andyliuxp** [p0ise/wine-novnc-docker#9]
你好，哥们，
首先请教一下您这套wine是什么版本呀？？、
再来能不能给一个安装 步骤呀？
我pull下来之后不知道去哪里修改vnc_password文件。
运行报错如下：
docker run -p 6080:6080 -p 5901:5901 --secret id=vnc_password,src=./vnc_password.txt wine-novnc
unknown flag: --secret
See 'docker run --help'.
请问下该如何 解决。
感谢 ，麻烦费心。

**Comment by p0ise** [comment]
你可以看看新的文档，我上午刚发布了一版更新，之前的文档有点问题

**Comment by andyliuxp** [comment]
好的，谢谢

**Comment by andyliuxp** [comment]
哥们，你好，
按您最新的说明运行出现这个错误：
Unable to find image 'wine-novnc:latest' locally
运行用的命令就是从你说明里复制的。
当然，镜像已经拉下来了。

docker pull invelop/wine-novnc:latest
latest: Pulling from invelop/wine-novnc
Digest: sha256:d59090839ab93783a2d72df9ebb792149bc8796558a129984775b6be8b4cbb1c
Status: Image is up to date for invelop/wine-novnc:latest

**Comment by p0ise** [comment]
> 哥们，你好， 按您最新的说明运行出现这个错误： Unable to find image 'wine-novnc:latest' locally 运行用的命令就是从你说明里复制的。 当然，镜像已经拉下来了。
> 
> docker pull invelop/wine-novnc:latest latest: Pulling from invelop/wine-novnc Digest: sha256:d59090839ab93783a2d72df9ebb792149bc8796558a129984775b6be8b4cbb1c Status: Image is up to date for invelop/wine-novnc:latest

这个是因为拉取的远程镜像带了我的用户名，但是我后面的命令是基于本地构建的镜像编写的，你只需要使用完整的镜像名`invelop/wine-novnc`就可以了。我也更新了我的文档，现在都使用相同的名称了。

**Comment by andyliuxp** [comment]
好，谢了兄弟 。
经测试可以运行了。
